version: '2'

networks:
  test-network:
    driver: bridge
    
services:

  tests:
    build: .
    command: python -m unittest discover -s tests -p "*.py"
    depends_on: 
      - dynamodb    
    networks:
      - test-network
    volumes:
      - ./:/usr/src/app:ro
    environment: 
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_SECRET_ACCESS_KEY=foobar 
      - DYNAMODB_ENDPOINT=http://dynamodb:4566

  dynamodb:
    image: localstack/localstack:0.11.1
    environment:
      - SEVRVICES=dynamodb
    ports:
      - 4566:4566 
      - 4569:4569
    networks:
      test-network:
        aliases: 
          - dynamodb
