name: Python package

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
      - uses: actions/checkout@v2
      - name: Run the tests with docker-compose
        run: docker-compose run tests
